### ISSUE TITLE
[IMPROVEMENT] Add Spring Data to the project.

### ISSUE THREAD

**Issue by romankh3** [Hexronimo/mushrooms_qualifier#1]
Hello, @Hexronimo!
As I can see. you're using hibernate.
I'd like you to add Spring data. What do you think about it?

**Comment by Hexronimo** [comment]
Github doesn't tell me when someone adds a new Issues, this is what I think. You wrote it on November 10, and I found it today - January 1.
In any case, I do not want to spend more time developing this qualifier; it is too bad in many respects, even its idea. But I will probably use Spring in some new projects.

**Comment by Hexronimo** [comment]
I tried Repository from SpringData and they are awesome!

**Comment by romankh3** [comment]
> I tried Repository from SpringData and they are awesome!
> 
> Those finnish-like long talking names ♥♥ findByDateStartBetweenOrderByDateStartAscTimeStartAsc(from, to) 

It’s really powerful tool for persistence. You can use it with almost all the cases.
